version: 2.1

jobs:
  issue-opened:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo "A new issues has been opened - we can send a slack notification,email, etc"

workflows:
  issue-opened:
    jobs:
      - issue-opened
